class WordGen{
    constructor(){
        this.wordList = [
            // Borrowed from xkcd password generator which borrowed it from wherever
            "ability","able","aboard","about","above","accept","accident","according",
            "account","accurate","acres","across","act","action","active","activity",
            "actual","actually","add","addition","additional","adjective","adult","adventure",
            "animal","announced","another","answer","ants","any","anybody","anyone",
            "anything","anyway","anywhere","apart","apartment","appearance","apple","applied",
            "appropriate","are","area","arm","army","around","arrange","arrangement",
            "arrive","arrow","art","article","as","aside","ask","asleep",
            "at","ate","atmosphere","atom","atomic","attached","attack","attempt",
            "attention","audience","author","automobile","available","average","avoid","aware",
            "away","baby","back","bad","badly","bag","balance","ball",
            "balloon","band","bank","bar","bare","bark","barn","base",
            "baseball","basic","basis","basket","bat","battle","be","bean",
            "bear","beat","beautiful","beauty","became","because","become","becoming",
            "bee","been","before","began","beginning","begun","behavior","behind",
            "being","believed","bell","belong","below","belt","bend","beneath",
            "bent","beside","best","bet","better","between","beyond","bicycle",
            "bigger","biggest","bill","birds","birth","birthday","bit","bite",
            "black","blank","blanket","blew","blind","block","blood","blow",
            "blue","board","boat","body","bone","book","border","born",
            "both","bottle","bottom","bound","bow","bowl","box","boy",
            "brain","branch","brass","brave","bread","break","breakfast","breath",
            "breathe","breathing","breeze","brick","bridge","brief","bright","bring",
            "broad","broke","broken","brother","brought","brown","brush","buffalo",
            "build","cotton","could","count","country","couple","courage","course","court",
            "cover","cow","cowboy","crack","cream","create","creature","crew",
            "crop","cross","crowd","cry","cup","curious","current","curve",
            "customs","cut","cutting","daily","damage","dance","danger","dangerous",
            "dark","darkness","date","daughter","dawn","day","dead","deal",
            "dear","death","decide","declared","deep","deeply","deer","definition",
            "degree","depend","depth","describe","desert","design","desk","detail",
            "determine","develop","development","diagram","diameter","did","die","differ",
            "difference","different","difficult","difficulty","dig","dinner","direct","direction",
            "directly","dirt","dirty","disappear","discover","discovery","discuss","discussion",
            "disease","dish","distance","distant","divide","division","do","doctor",
            "does","dog","doing","doll","dollar","done","donkey","door",
            "dot","double","doubt","down","dozen","draw","drawn","dream",
            "dress","drew","dried","drink","drive","driven","driver","driving",
            "drop","dropped","drove","dry","duck","due","dug","dull",
            "during","dust","duty","each","eager","ear","earlier","early",
            "earn","earth","easier","easily","east","easy","eat","eaten",
            "edge","education","effect","effort","egg","eight","either","electric",
            "electricity","element","elephant","eleven","else","empty","end","enemy",
            "energy","engine","engineer","enjoy","enough","enter","entire","entirely",
            "environment","equal","equally","equator","equipment","escape","especially","essential",
            "establish","even","evening","event","eventually","ever","every","everybody",
            "everyone","everything","everywhere","evidence","exact","exactly","examine","example",
            "excellent","except","exchange","excited","excitement","exciting","exclaimed","exercise",
            "exist","expect","experience","experiment","explain","explanation","explore","express",
            "expression","extra","eye","face","facing","fact","factor","factory",
            "failed","fair","fairly","fall","fallen","familiar","family","famous",
            "far","farm","farmer","farther","fast","fastened","faster","fat",
            "father","favorite","fear","feathers","feature","fed","feed","feel",
            "feet","fell","fellow","felt","fence","few","fewer","field",
            "fierce","fifteen","fifth","fifty","fight","fighting","figure","fill",
            "film","final","finally","find","fine","finest","finger","finish",
            "fire","fireplace","firm","first","fish","five","fix","flag",
            "flame","flat","flew","flies","flight","floating","floor","flow",
            "flower","fly","fog","folks","follow","food","foot","football",
            "for","force","foreign","forest","forget","forgot","forgotten","form",
            "former","fort","forth","forty","forward","fought","found","four",
            "fourth","fox", "promised","proper","properly","property","protection",
            "proud","prove","provide","public","pull","pupil","pure","purple",
            "purpose","push","put","putting","quarter","queen","question","quick",
            "quickly","quiet","quietly","quite","rabbit","race","radio","railroad",
            "rain","raise","ran","ranch","range","rapidly","rate","rather",
            "raw","rays","reach","read","reader","ready","real","realize",
            "rear","reason","recall","receive","recent","recently","recognize","record",
            "red","refer","refused","region","regular","related","relationship","religious",
            "remain","remarkable","remember","remove","repeat","replace","replied","report",
            "represent","require","research","respect","rest","result","return","review",
            "rhyme","rhythm","rice","rich","ride","riding","right","ring",
            "rise","rising","river","road","roar","rock","rocket","rocky",
            "rod","roll","roof","room","root","rope","rose","rough",
            "round","route","row","rubbed","rubber","rule","ruler","run",
            "running","rush","sad","saddle","safe","safety","said","sail",
            "sale","salmon","salt","same","sand","sang","sat","satellites",
            "satisfied","save","saved","saw","say","scale","scared","scene",
            "use","useful","using","usual","usually","valley","valuable","value",
            "vapor","variety","various","vast","vegetable","verb","vertical","very",
            "vessels","victory","view","village","visit","visitor","voice","volume",
            "vote","vowel","voyage","wagon","wait","walk","wall","want",
            "war","warm","warn","was","wash","waste","watch","water",
            "wave","way","we","weak","wealth","wear","weather","week",
            "weigh","weight","welcome","well","went","were","west","western",
            "wet","whale","what","whatever","wheat","wheel","when","whenever",
            "where","wherever","whether","which","while","whispered","whistle","white",
            "who","whole","whom","whose","why","wide","widely","wife",
            "wild","will","willing","win","wind","window","wing","winter",
            "wire","wise","wish","with","within","without","wolf","women",
            "won","wonder","wonderful","wood","wooden","wool","word","wore",
            "work","worker","world","worried","worry","worse","worth","would",
            "wrapped","write","writer","writing","written","wrong","wrote","yard",
            "year","yellow","yes","yesterday","yet","you","young","younger",
            "your","yourself","youth","zero","zebra","zipper","zoo","zulu"
          ];
          this.suffList = ['Inc', 'Industries', 'Resources', 'Ltd', 'Exploration', 'Materials', 'Resources', 'Minerals'];
    }
    getWord(){
        let word = this.wordList[Math.floor(Math.random()*this.wordList.length)];
        word = word.split("");
        word[0] = word[0].toUpperCase();
        word = word.join("");
        let suff = this.suffList[Math.floor(Math.random()*this.suffList.length)];
        word += " " + suff;
        return word;
    }


}